### PR TITLE
HTML & CSS project: Apple website clone

### PR DESCRIPTION
**Pull request by AndreasGalster**
Hi dear microverse code reviewer :).

A few notes on implementation:

- This pull request is for the apple website.
- We've used grid, flexbox and backgrounds/gradients for the page
- We load individual styles via @import
  - We know this is bad practice in normal css but in a production project this would be a @import with .scss and would bundle it all up into one file
- All linting tests are passing
- We commit the prettier.config.json file to our repo because otherwise prettier & husky doesn't work.
  - The config + the yarn.lock file are added to the project on purpose, because[ that's best practice to avoid dependency issues](https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494#:~:text=You%20should%20commit%201%20dependency,build%20%2B%20develop%20a%20project%20with.&text=lock%20should%20be%20committed%2C%20if,you%20commit%20both%20the%20yarn.)

### CODE REVIEW

**Review by SafaErden — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️

**Hi TEAM, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find the comments below**
##

**REQUIRED CHANGES**

- [ ] Make sure that basic CSS bad practices are not used ([article for support](https://speckyboy.com/good-bad-css-practices) ) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright) You repeat the same rules (such as width: 100%) in your CSS files. Please kindly apply DRY CSS rules.

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review once you are ready💪*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/)

Happy coding_ 👨‍💻 

**Safa ERDEN**

**Comment by yokoworks** [comment]
We fixed CSS files.
Could you check again, please?

**Comment by umairarshadbutt** [comment]
##
## Pull Request under review by Umair Arshad (TSE)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
### The [clone](https://raw.githack.com/AndreasGalster/mv-apple/apple/index.html) shows a good understanding of Backgrounds and Gradients. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks @AndreasGalster and @yocosaka :1st_place_medal:
##
**If you have any questions, let me know on slack at any time. I will be happy to help.**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
